name: ai_tools

services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: unless-stopped
    environment:
      # Reverse Proxy Settings
      - USE_X_FORWARDED_HOST=true
      - USE_X_FORWARDED_PROTO=true
    volumes:
      - ${BASE_PATH_OPENWEBUI}:/app/backend/data
    ports:
      - ${OPENWEBUI_PORT}:8080

networks:
  default:
    ipam:  
      driver: default
      config: 
        - subnet: ${SUBNET}
