name: postgres

services:
  postgres-db:
    image: postgres:latest
    container_name: training-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - /opt/postgres:/var/lib/postgresql
    restart: always
    networks:
      - default

networks:
  default:
    ipam:  
      driver: default
      config: 
        - subnet: ${SUBNET}