name: gitea

services:
  server:
    image: docker.gitea.com/gitea:1.24.3
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:${DB_PORT}
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=${USER}
      - GITEA__database__PASSWD=${PASSWORD}
      - GITEA__server__ROOT_URL=${ROOT_URL}
    restart: always
    volumes:
      - ${MAIN_PATH}/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - ${GITEA_WEBUI_PORT}:3000
      - ${GITEA_SSH_PORT}:22
    depends_on:
      - db

  db:
    image: docker.io/library/postgres:14
    container_name: gitea_db
    restart: always
    environment:
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_DB=gitea
    volumes:
      - ${MAIN_PATH}/postgres:/var/lib/postgresql/data'
    ports:
      - ${DB_PORT}:5432

networks:
  default:
    ipam:  
      driver: default
      config: 
        - subnet: ${SUBNET}