name: jenkins

services:
  jenkins-dind:
    image: docker:dind
    container_name: jenkins-dind
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=${DOCKER_TLS_CERTDIR}
    volumes:
      - /opt/jenkins/certs:/certs/client
      - /opt/jenkins/jenkins_home:/var/jenkins_home
    ports:
      - "${DAEMON_PORT}:2376"
    command: ["--storage-driver", "overlay2"]
    restart: unless-stopped

  jenkins:
    image: myjenkins-blueocean:2.504.3-1
    container_name: jenkins
    environment:
      - DOCKER_HOST=${DOCKER_HOST}
      - DOCKER_CERT_PATH=${DOCKER_CERT_PATH}
      - DOCKER_TLS_VERIFY=${DOCKER_TLS_VERIFY}
    user: root
    volumes:
      - /opt/jenkins/jenkins_home:/var/jenkins_home
      - /opt/jenkins/certs:/certs/client:ro
    ports:
      - ${JENKINS_WEBUI_PORT}:8080
      - ${TCP_PORT}:50000
    restart: on-failure

  agent:
    image: jenkins/ssh-agent
    container_name: jenkins-agent
    privileged: true
    user: root
    ports:
      - ${AGENT_SSH_PORT}:22
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=${JENKINS_AGENT_SSH_PUBLIC_KEY}

networks:
  default:
    ipam:  
      driver: default
      config: 
        - subnet: ${SUBNET}