name: utils

services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:lts
    deploy:
      resources:
        limits:
          cpus: '${PORTAINER_CPU_LIMIT:-0.5}'
          memory: '${PORTAINER_MEM_LIMIT:-512M}'
        reservations:
          cpus: '${PORTAINER_CPU_RESERV:-0.1}'
          memory: '${PORTAINER_MEM_RESERV:-128M}'
    ports:
      - ${PORTAINER_HTTPS_PORT}:9443
      - ${PORTAINER_PORT}:8000
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${BASE_PATH_PORTAINER}/data:/data
    networks:
      - default

  grafana:
    image: grafana/grafana
    container_name: grafana
    deploy:
      resources:
        limits:
          cpus: '${GRAFANA_CPU_LIMIT:-0.5}'
          memory: '${GRAFANA_MEM_LIMIT:-1G}'
        reservations:
          cpus: '${GRAFANA_CPU_RESERV:-0.2}'
          memory: '${GRAFANA_MEM_RESERV:-256M}'
    restart: unless-stopped
    volumes:
      - ${BASE_PATH_GRAFANA}:/var/lib/grafana
    ports:
     - ${GRAFANA_WEBUI_PORT}:3000
    networks:
      - default

networks:
  default:
    ipam:  
      driver: default
      config: 
        - subnet: ${SUBNET}